In [3]:
import pandas as pd
df = pd.read_csv("data/ai_company_adoption.csv")
df

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
0,1,COMP-00001,2023,Q1,Italy,Europe,Education,Startup,57,48.31,...,2.65,1,1,3,2.52,9.45,53,5.20,WEF Survey,API Scrape
1,2,COMP-00001,2023,Q2,Italy,Europe,Education,Startup,57,48.31,...,5.77,2,2,5,4.77,0.00,51,6.98,McKinsey Report,Phone Interview
2,3,COMP-00001,2023,Q3,Italy,Europe,Education,Startup,57,48.31,...,6.94,3,3,2,12.87,9.74,40,4.12,Internal Corporate Survey,Research Compilation
3,4,COMP-00001,2023,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.32,1,1,2,8.19,0.00,51,5.72,Internal Corporate Survey,Research Compilation
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,159996,COMP-10000,2025,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,19.01,1292,1027,1766,9.44,9.52,62,5.68,McKinsey Report,Phone Interview
149996,159997,COMP-10000,2026,Q1,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,15.56,466,883,803,10.65,6.94,56,5.57,Internal Corporate Survey,Research Compilation
149997,159998,COMP-10000,2026,Q2,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,13.38,1360,1474,1779,5.52,0.32,48,7.56,WEF Survey,API Scrape
149998,159999,COMP-10000,2026,Q3,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,12.75,1358,887,1648,11.87,7.85,69,6.00,WEF Survey,Research Compilation
149999,160000,COMP-10000,2026,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,14.42,1529,1501,2409,11.89,10.82,65,7.30,WEF Survey,API Scrape

In [4]:
df.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
0,1,COMP-00001,2023,Q1,Italy,Europe,Education,Startup,57,48.31,...,2.65,1,1,3,2.52,9.45,53,5.20,WEF Survey,API Scrape
1,2,COMP-00001,2023,Q2,Italy,Europe,Education,Startup,57,48.31,...,5.77,2,2,5,4.77,0.00,51,6.98,McKinsey Report,Phone Interview
2,3,COMP-00001,2023,Q3,Italy,Europe,Education,Startup,57,48.31,...,6.94,3,3,2,12.87,9.74,40,4.12,Internal Corporate Survey,Research Compilation
3,4,COMP-00001,2023,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.32,1,1,2,8.19,0.00,51,5.72,Internal Corporate Survey,Research Compilation
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation

In [5]:
df.tail()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
149995,159996,COMP-10000,2025,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,19.01,1292,1027,1766,9.44,9.52,62,5.68,McKinsey Report,Phone Interview
149996,159997,COMP-10000,2026,Q1,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,15.56,466,883,803,10.65,6.94,56,5.57,Internal Corporate Survey,Research Compilation
149997,159998,COMP-10000,2026,Q2,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,13.38,1360,1474,1779,5.52,0.32,48,7.56,WEF Survey,API Scrape
149998,159999,COMP-10000,2026,Q3,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,12.75,1358,887,1648,11.87,7.85,69,6.00,WEF Survey,Research Compilation
149999,160000,COMP-10000,2026,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,14.42,1529,1501,2409,11.89,10.82,65,7.30,WEF Survey,API Scrape

In [ ]:
df.shape

(150000, 43)

In [7]:
df.describe()

,response_id,survey_year,num_employees,annual_revenue_usd_millions,company_founding_year,company_age,ai_adoption_rate,years_using_ai,num_ai_tools_used,ai_projects_active,...,task_automation_rate,time_saved_per_week,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,79961.106207,2024.500987,2342.376580,1180.345751,2005.993767,18.507220,36.414726,4.931580,2.315120,6.270693,...,19.761744,6.267406,9.266996,111.36984,117.882507,181.642700,4.606486,4.814909,55.199920,5.420619
std,46158.813039,1.118013,4754.424755,2391.471420,9.473220,9.539367,14.544096,2.429316,0.946826,3.500142,...,9.222562,2.977495,5.637067,255.83778,261.650245,417.929587,5.318773,3.383086,8.593423,1.047142
min,1.000000,2023.000000,10.000000,1.010000,1990.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-5.000000,0.000000,40.000000,1.000000
25%,40020.750000,2024.000000,69.000000,33.880000,1998.000000,10.000000,26.430000,3.000000,2.000000,4.000000,...,13.360000,4.180000,5.070000,2.00000,3.000000,3.000000,0.780000,2.120000,49.000000,4.700000
50%,79937.500000,2025.000000,349.000000,184.160000,2006.000000,18.000000,36.320000,5.000000,2.000000,6.000000,...,19.700000,6.230000,9.060000,10.00000,12.000000,16.000000,4.480000,4.620000,55.000000,5.410000
75%,119913.250000,2026.000000,884.000000,444.150000,2014.000000,27.000000,46.200000,7.000000,3.000000,9.000000,...,26.020000,8.290000,13.120000,41.00000,41.000000,64.000000,8.240000,7.130000,61.000000,6.130000
max,160000.000000,2026.000000,19970.000000,9996.730000,2022.000000,36.000000,100.000000,10.000000,6.000000,20.000000,...,59.630000,19.150000,34.360000,2417.00000,1980.000000,3881.000000,30.000000,20.790000,97.000000,9.760000

In [9]:
df

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
0,1,COMP-00001,2023,Q1,Italy,Europe,Education,Startup,57,48.31,...,2.65,1,1,3,2.52,9.45,53,5.20,WEF Survey,API Scrape
1,2,COMP-00001,2023,Q2,Italy,Europe,Education,Startup,57,48.31,...,5.77,2,2,5,4.77,0.00,51,6.98,McKinsey Report,Phone Interview
2,3,COMP-00001,2023,Q3,Italy,Europe,Education,Startup,57,48.31,...,6.94,3,3,2,12.87,9.74,40,4.12,Internal Corporate Survey,Research Compilation
3,4,COMP-00001,2023,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.32,1,1,2,8.19,0.00,51,5.72,Internal Corporate Survey,Research Compilation
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,159996,COMP-10000,2025,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,19.01,1292,1027,1766,9.44,9.52,62,5.68,McKinsey Report,Phone Interview
149996,159997,COMP-10000,2026,Q1,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,15.56,466,883,803,10.65,6.94,56,5.57,Internal Corporate Survey,Research Compilation
149997,159998,COMP-10000,2026,Q2,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,13.38,1360,1474,1779,5.52,0.32,48,7.56,WEF Survey,API Scrape
149998,159999,COMP-10000,2026,Q3,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,12.75,1358,887,1648,11.87,7.85,69,6.00,WEF Survey,Research Compilation
149999,160000,COMP-10000,2026,Q4,Nigeria,Africa,Healthcare,Enterprise,18038,2040.01,...,14.42,1529,1501,2409,11.89,10.82,65,7.30,WEF Survey,API Scrape

In [8]:
df.isnull().sum()

response_id                    0
company_id                     0
survey_year                    0
quarter                        0
country                        0
region                         0
industry                       0
company_size                   0
num_employees                  0
annual_revenue_usd_millions    0
company_founding_year          0
company_age                    0
company_age_group              0
ai_adoption_rate               0
ai_adoption_stage              0
years_using_ai                 0
ai_primary_tool                0
num_ai_tools_used              0
ai_use_case                    0
ai_projects_active             0
ai_training_hours              0
ai_budget_percentage           0
ai_maturity_score              0
ai_failure_rate                0
ai_investment_per_employee     0
regulatory_compliance_score    0
data_privacy_level             0
ai_ethics_committee            0
ai_risk_management_score       0
remote_work_percentage         0
employee_satisfaction_score    0
task_automation_rate           0
time_saved_per_week            0
productivity_change_percent    0
jobs_displaced                 0
jobs_created                   0
reskilled_employees            0
revenue_growth_percent         0
cost_reduction_percent         0
innovation_score               0
customer_satisfaction          0
survey_source                  0
data_collection_method         0
dtype: int64

In [10]:
df["survey_year"].unique()

array([2023, 2024, 2025, 2026])

In [11]:
df["company_id"].unique()

<StringArray>
['COMP-00001', 'COMP-00002', 'COMP-00003', 'COMP-00004', 'COMP-00005',
 'COMP-00006', 'COMP-00007', 'COMP-00008', 'COMP-00009', 'COMP-00010',
 ...
 'COMP-09991', 'COMP-09992', 'COMP-09993', 'COMP-09994', 'COMP-09995',
 'COMP-09996', 'COMP-09997', 'COMP-09998', 'COMP-09999', 'COMP-10000']
Length: 10000, dtype: str

In [13]:
df["country"].unique()

<StringArray>
[       'Italy',           'UK',      'Germany',          'USA',
        'Chile',  'Philippines', 'South Africa',        'India',
     'Thailand',     'Malaysia',       'Sweden',        'Spain',
        'Egypt',  'Netherlands',     'Colombia',       'Canada',
    'Australia',    'Indonesia',    'Singapore',        'China',
      'Vietnam',      'Nigeria',        'Japan',       'Brazil',
  'New Zealand',       'Poland',    'Argentina',  'South Korea',
       'France',        'Kenya']
Length: 30, dtype: str

In [19]:
print(df.loc[df.duplicated(keep=False)])

Empty DataFrame
Columns: [response_id, company_id, survey_year, quarter, country, region, industry, company_size, num_employees, annual_revenue_usd_millions, company_founding_year, company_age, company_age_group, ai_adoption_rate, ai_adoption_stage, years_using_ai, ai_primary_tool, num_ai_tools_used, ai_use_case, ai_projects_active, ai_training_hours, ai_budget_percentage, ai_maturity_score, ai_failure_rate, ai_investment_per_employee, regulatory_compliance_score, data_privacy_level, ai_ethics_committee, ai_risk_management_score, remote_work_percentage, employee_satisfaction_score, task_automation_rate, time_saved_per_week, productivity_change_percent, jobs_displaced, jobs_created, reskilled_employees, revenue_growth_percent, cost_reduction_percent, innovation_score, customer_satisfaction, survey_source, data_collection_method]
Index: []

[0 rows x 43 columns]

In [20]:
df["country"].value_counts()

country
France          5637
Japan           5629
South Korea     5443
Germany         5327
Chile           5190
Egypt           5125
Netherlands     5118
Philippines     5091
Poland          5086
USA             5058
New Zealand     5058
UK              5027
South Africa    5003
Italy           4963
Australia       4944
India           4941
Colombia        4918
Indonesia       4915
Brazil          4907
Argentina       4894
Sweden          4881
Kenya           4871
Singapore       4854
Spain           4796
Nigeria         4788
Thailand        4782
Malaysia        4718
Canada          4682
China           4677
Vietnam         4677
Name: count, dtype: int64

In [21]:
df.dtypes

response_id                      int64
company_id                         str
survey_year                      int64
quarter                            str
country                            str
region                             str
industry                           str
company_size                       str
num_employees                    int64
annual_revenue_usd_millions    float64
company_founding_year            int64
company_age                      int64
company_age_group                  str
ai_adoption_rate               float64
ai_adoption_stage                  str
years_using_ai                   int64
ai_primary_tool                    str
num_ai_tools_used                int64
ai_use_case                        str
ai_projects_active               int64
ai_training_hours              float64
ai_budget_percentage           float64
ai_maturity_score              float64
ai_failure_rate                float64
ai_investment_per_employee     float64
regulatory_compliance_score      int64
data_privacy_level                 str
ai_ethics_committee                str
ai_risk_management_score         int64
remote_work_percentage         float64
employee_satisfaction_score    float64
task_automation_rate           float64
time_saved_per_week            float64
productivity_change_percent    float64
jobs_displaced                   int64
jobs_created                     int64
reskilled_employees              int64
revenue_growth_percent         float64
cost_reduction_percent         float64
innovation_score                 int64
customer_satisfaction          float64
survey_source                      str
data_collection_method             str
dtype: object

In [22]:
df.describe()

,response_id,survey_year,num_employees,annual_revenue_usd_millions,company_founding_year,company_age,ai_adoption_rate,years_using_ai,num_ai_tools_used,ai_projects_active,...,task_automation_rate,time_saved_per_week,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,79961.106207,2024.500987,2342.376580,1180.345751,2005.993767,18.507220,36.414726,4.931580,2.315120,6.270693,...,19.761744,6.267406,9.266996,111.36984,117.882507,181.642700,4.606486,4.814909,55.199920,5.420619
std,46158.813039,1.118013,4754.424755,2391.471420,9.473220,9.539367,14.544096,2.429316,0.946826,3.500142,...,9.222562,2.977495,5.637067,255.83778,261.650245,417.929587,5.318773,3.383086,8.593423,1.047142
min,1.000000,2023.000000,10.000000,1.010000,1990.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-5.000000,0.000000,40.000000,1.000000
25%,40020.750000,2024.000000,69.000000,33.880000,1998.000000,10.000000,26.430000,3.000000,2.000000,4.000000,...,13.360000,4.180000,5.070000,2.00000,3.000000,3.000000,0.780000,2.120000,49.000000,4.700000
50%,79937.500000,2025.000000,349.000000,184.160000,2006.000000,18.000000,36.320000,5.000000,2.000000,6.000000,...,19.700000,6.230000,9.060000,10.00000,12.000000,16.000000,4.480000,4.620000,55.000000,5.410000
75%,119913.250000,2026.000000,884.000000,444.150000,2014.000000,27.000000,46.200000,7.000000,3.000000,9.000000,...,26.020000,8.290000,13.120000,41.00000,41.000000,64.000000,8.240000,7.130000,61.000000,6.130000
max,160000.000000,2026.000000,19970.000000,9996.730000,2022.000000,36.000000,100.000000,10.000000,6.000000,20.000000,...,59.630000,19.150000,34.360000,2417.00000,1980.000000,3881.000000,30.000000,20.790000,97.000000,9.760000